name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run checks and Build APK
        # We added 'assembleFlossDebug' to specifically build the FLOSS version you use
        run: ./gradlew evaluateViolations testDebugUnitTest testFlossDebugUnitTest assembleFlossDebug -s

      - name: Upload Transparent APK
        uses: actions/upload-artifact@v4
        with:
          name: OpenLinkWith-Transparent-Build
          # This wildcard path finds the APK regardless of which module it's in
          path: "**/build/outputs/apk/**/*.apk"
